name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - name: py27
            os: ubuntu-20.04
            python-version: "2.7"
          - name: py35
            os: ubuntu-20.04
            python-version: "3.5"
          - name: py36
            os: ubuntu-20.04
            python-version: "3.6"
          - name: macos
            os: macos-latest
            python-version: "3.x"
          - name: windows
            os: windows-latest
            python-version: "3.x"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os}}-pip-${{ matrix.python-version }}
          path: ~/.cache/pip
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: lsb_release -a
        if: startsWith(matrix.os, 'ubuntu')
      - run: uname -a
        if: startsWith(matrix.os, 'ubuntu')
      - run: python --version
      - name: Install dependencies
        run: |
          pip install -U pytest pytest-cov codecov coveralls
          pip install scrutinizer-ocular
      - name: Install package
        run: |
          pip install -e ".[all]"
      - run: pip list
      - name: Test
        run: |
          python -m coverage run --parallel-mode --source=src -m pytest -v --doctest-glob='*.md'
      - name: Combine and convert coverage
        run: |
          python -m coverage combine
          python -m coverage report
          python -m coverage xml -i
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3

      - name: Upload to Coveralls
        if: startsWith(matrix.os, 'ubuntu') && matrix.python-version != '2.7'
        run: |
          python -m coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: py${{ matrix.python-version }}

  coverage:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Finish coverage collection
        run: |
          python -m pip install -U pip
          python -m pip install -U coveralls
          python -m coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
